config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => ENV['RAILS_DEFAULT_URL']

  root to: "contacts#index"
  resources :contacts, only: [:index]
  namespace :imported_files do
   get 'index'
   get 'upload'
   post 'import'
  end

  get 'imported_files/:id', to: 'imported_files#show', as: :imported_files_show

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates_presence_of :name, :dob, :phone, :address, :credit_card, :email, :user

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: { scope: :user_id }
  validate :check_credit_card
  validate :dob_is_iso8601

  validates_format_of :name, with: /\A([^-]+)\z/
  validates_format_of :phone, with: /\A(\(\+\d{1,3}\)\d{3}-\d{3}-\d{2}-\d{2}|\(\+\d{1,3}\)\d{3}\s\d{3}\s\d{2}\s\d{2})\z/

  before_save :set_franchise

  private

  def check_credit_card
    cleaned_number = credit_card&.delete('^0-9')
    cleaned_number.credit_card_bin.present?
  rescue
    errors.add(:credit_card, 'invalid')
  end

  def dob_is_iso8601
    Date.iso8601(dob.to_s)
  rescue
    errors.add(:dob, 'invalid')
  end

  def set_franchise
    cleaned_number = credit_card&.delete('^0-9')
    self.franchise = cleaned_number&.credit_card_bin_brand
  rescue
    self.franchise = ''
  end
end

app/models/import_summary.rb
class ImportSummary < ApplicationRecord
  belongs_to :imported_file
end

app/models/imported_file.rb
class ImportedFile < ApplicationRecord
  belongs_to :user
  has_many :import_summaries

  enum status: %i[on_hold processing failed finished]

  has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :imported_files
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts = current_user.contacts.order(:name).page(params[:page]).per(10)
  end
end

app/controllers/imported_files_controller.rb
class ImportedFilesController < ApplicationController
  before_action :import_params, only: [:import]

  def index
    @imported_files = current_user.imported_files.order(created_at: :desc).page(params[:page]).per(10)
  end

  def upload
    @columns = valid_columns
  end

  def import
    if params['csv_file'].present?
      create_imported_file
      notice = 'CSV file is being processed'
      path = imported_files_index_path
    else
      path = imported_files_upload_path
      notice = 'Error, No file selected'
    end

    redirect_to path, flash: { notice: notice }
  end

  def show
    @summary = ImportedFile.find(params[:id]).import_summaries.first
  end

  private

  def import_params
    params.permit(
      permitted_params
    )
  end

  def permitted_params
    form_fields = []
    valid_columns.each_with_index do |col, index|
      form_fields.push("col_#{index}")
      form_fields.push("input_#{index}")
    end

    form_fields
  end

  def create_imported_file
    imported_file = current_user.imported_files.create(
      file_name: params['csv_file'].original_filename,
      status: :on_hold,
      file: params['csv_file']
    )

    CsvGeneratorJob.perform_later(imported_file.id, import_params)
  end

  def valid_columns
    Contact.column_names.reject { |column| %w[id franchise created_at updated_at user_id].include?(column) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<%= render partial: 'partials/menu' %>
<div class="row">
  <h1 class="center">Contacts</h1>
  <%= link_to "Import Contacts" , imported_files_upload_path %>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Credit Card</th>
        <th>Franchise</th>
        <th>Day of birth </th>
        <th>Address</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |c| %>
        <tr>
          <td><%= c.name %></td>
          <td><%= c.email %></td>
          <td><%= c.phone %></td>
          <td><%= c.credit_card %></td>
          <td><%= c.franchise %></td>
          <td><%= c.dob %></td>
          <td><%= c.address %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-center">
    <%= render 'partials/paginate', object: @contacts, left: 2, right: 2 %>
  </div>
</div>

app/views/home/index.html.erb
<%= render partial: 'partials/menu' %>
<div class="row">
  <p>Welcome</p>
</div>

app/views/imported_files/index.html.erb
<%= render partial: 'partials/menu' %>
<div class="row">
  <h1>Imported Files</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Action</th>
        <th>File Name</th>
        <th>Status</th>
        <th>Created at</th>
      </tr>
    </thead>
    <tbody>
      <% @imported_files.each do |imp| %>
        <tr>
          <td>
            <% if imp.import_summaries.any? %>
              <%= link_to "View", imported_files_show_path(imp) %>
            <% else %>
              View
            <% end %>
            
          </td>
          <td><%= link_to imp.file_name, url_for(imp.file) %></td>
          <td><%= imp.status %></td>
          <td><%= imp.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-center">
    <%= render 'partials/paginate', object: @imported_files, left: 2, right: 2 %>
  </div>
</div>

app/views/imported_files/show.html.erb
<%= render partial: 'partials/menu' %>
<div class="row">
  <h1><%= @summary.imported_file.file_name %></h1>
  <h3>Estatus: <%= @summary.imported_file.status %></h3>
  <strong>Stats: <%= @summary.stats %></strong>
  <br>
  <strong>Error: <%= @summary.messages %></strong>
  <br>
</div>

app/views/imported_files/upload.html.erb
<%= render partial: 'partials/menu' %>
<h1>Upload</h1>
<div class="row">
  <p>Upload a CSV file and set the columns per each the database field</p>
  <div class="d-flex justify-content-center">
    <%= form_tag imported_files_import_path, multipart: true do %>
      <div>
        <%= file_field_tag "csv_file", required: true %>
      </div>
      
      <div class="pt-3">
        <% @columns.each_with_index do |col,index| %>
          <%= select_tag("col_#{index}", options_for_select(@columns, col)) %> <%= text_field_tag "input_#{index}", nil ,required: true %><br>
        <% end %>
      </div>
    
      <div class="pt-4 d-grid col-12 mx-auto">
        <%= submit_tag "Upload",class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/cjs/popper.min.js" integrity="sha512-cccYINs21/woK1lZ16XmqaT6ohTy4BxrsgGrxnU3SEVKQACVUcU6nyPXb4meW0TG9TN9zj7OqaFK3E+ckKtmZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <%= yield %>
  </body>
</html>

app/views/partials/_menu.html.erb
<div class="d-flex justify-content-center">
  <ul class="nav">
    <li class="nav-item">
      <%= link_to "Home" , root_path, class: "nav-link active" %>
    </li>
    <li>
      <%= link_to "Contacts" , contacts_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Imported Files" , imported_files_index_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Logout', destroy_user_session_path, class: "nav-link" %>
    </li>
  </ul>
</div>

app/views/partials/_paginate.html.erb
<%= paginate object, left: left, right: right %>